# Generated by Django 3.0.5 on 2022-10-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221003_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
