# Generated by Django 3.0.5 on 2022-10-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
