# Generated by Django 3.0.5 on 2022-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
