# Generated by Django 3.0.5 on 2022-10-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customer_address2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
