# Generated by Django 3.0.5 on 2022-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.CharField(default=0, max_length=100)),
                ('address2', models.CharField(default=0, max_length=100)),
                ('city', models.CharField(default=0, max_length=100)),
                ('zip', models.IntegerField(default=0)),
            ],
        ),
    ]
