# Generated by Django 3.0.5 on 2022-10-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20221020_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='name',
        ),
    ]
