# Generated by Django 3.0.5 on 2022-10-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20221021_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(default='Thanks For Ordering with us. We will update the status soon', null=True),
        ),
    ]
