# Generated by Django 3.0.5 on 2022-10-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20221025_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=12, null=True),
        ),
    ]
