# Generated by Django 3.0.5 on 2022-11-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_order_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Invoice',
        ),
    ]
