# Generated by Django 3.0.5 on 2022-11-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_remove_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(default=1, max_length=12),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
